### ISSUE TITLE
GameSolver should not print anything to console

### ISSUE THREAD

**Issue by taveratch** [OOP2018/guessing-game-France98#4]
https://github.com/OOP2018/guessing-game-France98/blob/2f9cf70e73b60f615177b095a34425af4e7c1077/src/GameSolver.java#L21-L22

**Comment by taveratch** [comment]
Please do not close the issue without fixing.
GameSolver still print something to console.

**Comment by France98** [comment]
sorry about that, I misunderstand about the problem.
